FORMAT: 1A
HOST: https://auctionline-is2.herokuapp.com/

# API AuctiONline

Documentazione API AuctiONline. Le API permettono di gestire la compravendita di beni attraverso le aste.


## /api/v1/autenticazione

### Autentica utente [POST]

Verifica che le credenziali inserite dall'utente e in caso positiva crea un token di autenticazione per l'utente.

+ Request (application/json)

    + Attributes
        + username (required, string) - Username dell'utente
        + password (required, string) -Password dell'utente
      
+ Response 201 (application/json)

    Autenticazione avvenuta con successo. Invio token e redirect alla pagina del catalogo

    + Body
        {
            "success": true,
            "message": "Enjoy your token!",
            "token": token,
            "email": user.email,
            "id": user._id,
            "self": "api/v1/" + user._id
        }

+ Response 401 (application/json)

    Autenticazione fallita. Invio messaggio di errore

    + Body
        {
            "success": false, 
            "message": "Autenticazione fallita. Utente o password errati"
        }




## /api/v1/registrazione

### Registra utente [POST]

Verifica che l'utente non sia già registrato e che l'username sia inutilizzato da altri utenti. In caso affermativo crea il nuovo profilo e crea un token di autenticazione per l'utente appena registrato.

+ Request (application/json)

    + Attributes
        

+ Response 201 (application/json)

    + Body